### ISSUE TITLE
[Question] require.realms.modules - will it result in hacks?

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/browser-modules#2]
With the older namespaced JS style we used there was the ability to access any code from anywhere since it was on a global. With browser-modules the idea is to stop this. And the general use case will be that it will work well.

However, it will be possible to access things you're not supposed to via:

``` javascript
var Naughty = require.realm.modules[ 'path/to/something/I/should/not/access/hack' ];
var myNaughtyHack = new Naughty();
```

Is this something we should worry about?

_Oh, there's also a `realm` global. But since `realm.install` is called right after the `browser-modules.js` include I guess that's not a big deal._

**Comment by kybernetikos** [comment]
It's unlikely to result in hacks because it's obvious that it's a hack, so people are unlikely to do it.
Node.js has this exact same capability, but it doesn't tend to get used for hacks.

besides, there's nothing you can access through require.realm.modules that you can't access just by calling require.
